# Generated by Django 3.0.5 on 2020-07-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.TextField(max_length=150)),
                ('username', models.TextField(max_length=150)),
                ('phone', models.TextField()),
                ('password', models.TextField(max_length=15)),
            ],
        ),
    ]
